### ISSUE TITLE
File is missing

### ISSUE THREAD

**Issue by ArseniyStolyarov** [Koziev/rupostagger#4]
No file at https://drive.google.com/uc?id=1xlL8ijnwE6tAPpsil7Q1yWkXY4mn2YCd, 404 error.

**Comment by Koziev** [comment]
Sorry, I can not find this link anywhere in README.  
Can you show me where I can find it?

**Comment by ArseniyStolyarov** [comment]
Sorry, the problem seems to be with the ruword2tags part that tries to load ruword2tags.db from a given link. But link gives 404

**Comment by ArseniyStolyarov** [comment]
The file can be found here: https://huggingface.co/bogdal/ruword2tags/blob/main/ruword2tags.db
